// Image Generation tools (16-20)
export const imageTools = [
{
slug:'midjourney',name:'Midjourney',category:'image',icon:'🎨',iconBg:'rgba(0,0,0,0.12)',iconColor:'#FFFFFF',badge:'top',rating:4.8,priceLabel:'$10 – $120/mo',
description:'The highest-quality AI image generator, producing photorealistic and artistic images through Discord-based and web-based interfaces.',
keywords:['image generation','art','photorealistic','design','midjourney'],
verdict:'Best image quality in 2026 — period. Discord workflow is clunky but web app fixes it. $10/mo Basic handles most creative needs. Essential for designers and visual creatives.',
pros:['Highest image quality and aesthetic consistency among all generators','V6 model produces near-photorealistic images with excellent composition','Strong community with shared prompts and style references','Web app (2024+) finally offers a proper UI beyond Discord'],
cons:['No free tier — $10/mo minimum to start','Discord-based workflow alienates non-technical users','Limited control over specific compositions vs DALL-E editor','No API access for most plans — enterprise only'],
pricing:[{name:'Basic',price:'$10/mo',summary:'Casual creators.',featured:false,features:['200 images/mo','Discord + Web','Fast GPU hours: 3.3h/mo'],notIncluded:['Stealth mode','Max concurrent jobs']},{name:'Standard',price:'$30/mo',summary:'Regular creators.',featured:true,features:['Unlimited relaxed','15h fast GPU','Stealth mode available'],notIncluded:['Max concurrent']},{name:'Pro',price:'$60/mo',summary:'Professional creatives.',featured:false,features:['Unlimited relaxed','30h fast GPU','Stealth mode','12 concurrent jobs'],notIncluded:[]},{name:'Mega',price:'$120/mo',summary:'Studios and agencies.',featured:false,features:['Unlimited relaxed','60h fast GPU','Stealth mode','12 concurrent'],notIncluded:[]}],
personas:[{icon:'🎨',title:'Graphic designers',description:'Designers creating concept art, mood boards, and visual assets.'},{icon:'📸',title:'Marketing creatives',description:'Marketers generating campaign visuals and social media imagery.'},{icon:'🎮',title:'Game/concept artists',description:'Artists creating character designs, environments, and fantasy art.'}],
websiteUrl:'https://www.midjourney.com',scores:{price:62,ease:70,quality:98,integrations:35,support:55},
_engine:'Midjourney V6',_api:'Enterprise only',_mobile:'Discord/Web',_team:'No',_support:'Discord community',_privacy:'Standard',_integrations:'Discord, Web app',_offline:'No',_customTrain:'Style references',
body:`## Overview\n\nMidjourney is the gold standard for AI image generation in 2026. Created by David Holz's independent research lab, it consistently produces the most aesthetically pleasing images across all AI generators. The V6 model launched in late 2024 brought near-photorealistic quality.\n\n## Use Cases\n\nDesigners, marketers, and artists use Midjourney for concept art, campaign visuals, product mockups, and social media content. Reddit's r/midjourney (2M+ members) is one of the most active AI communities. Product Hunt rates it as the #1 AI image tool.\n\n## The Bottom Line\n\nIf image quality is your priority, Midjourney has no equal. $10/mo Basic covers casual needs. The Discord workflow is the main friction point — the web app is catching up. For programmatic image generation, use DALL-E 3's API instead.`
},
{
slug:'dall-e-3',name:'DALL-E 3',category:'image',icon:'🖼️',iconBg:'rgba(16,163,127,0.15)',iconColor:'#10A37F',rating:4.4,priceLabel:'Free (via ChatGPT) – API',
description:'OpenAI\'s image generator integrated directly into ChatGPT, offering conversational image creation with strong text rendering and editing capabilities.',
keywords:['image generation','openai','chatgpt','text rendering','api'],
verdict:'Best choice if you already use ChatGPT Plus. Conversational image editing is unique. API makes it the best programmatic option. Quality trails Midjourney for artistic work.',
pros:['Built into ChatGPT — no separate tool or subscription needed','Best text rendering in generated images among all AI generators','Conversational editing: describe changes and iterate naturally','Robust API for programmatic image generation at scale'],
cons:['Artistic quality and aesthetics trail Midjourney significantly','Content policies are the most restrictive of any generator','Limited style control compared to Stable Diffusion','API pricing can get expensive at volume'],
pricing:[{name:'Free',price:'$0',summary:'Limited via ChatGPT free.',featured:false,features:['Basic image generation','Limited daily creates'],notIncluded:['Unlimited generation','API access']},{name:'Via ChatGPT Plus',price:'$20/mo',summary:'Included with ChatGPT Plus.',featured:true,features:['DALL-E 3 in ChatGPT','Conversational editing','Unlimited creates'],notIncluded:['API access']},{name:'API',price:'Pay-per-use',summary:'$0.04-$0.12 per image.',featured:false,features:['Programmatic generation','All resolutions','Batch processing'],notIncluded:[]}],
personas:[{icon:'💬',title:'ChatGPT users',description:'Existing ChatGPT Plus subscribers who need occasional image generation.'},{icon:'👩‍💻',title:'Developers',description:'Engineers building apps that need programmatic image generation via API.'},{icon:'📝',title:'Content creators',description:'Writers and bloggers who need quick illustrations for their content.'}],
websiteUrl:'https://openai.com/dall-e-3',scores:{price:80,ease:92,quality:82,integrations:88,support:70},
_engine:'DALL-E 3',_api:'Yes (OpenAI API)',_mobile:'Via ChatGPT app',_team:'Via ChatGPT Team',_support:'OpenAI support',_privacy:'OpenAI policies',_integrations:'ChatGPT, API, Bing, Designer',_offline:'No',_customTrain:'No',
body:`## Overview\n\nDALL-E 3, OpenAI's third-generation image model, is uniquely positioned as the most accessible AI image generator — it's built directly into ChatGPT. Users describe what they want conversationally and iterate through edits naturally. Its text rendering capability (generating readable text in images) is best-in-class.\n\n## Use Cases\n\nChatGPT users generate images for blog headers, social media posts, presentations, and quick visualizations without leaving their chat. Developers use the API for programmatic generation in apps. r/ChatGPT users praise the conversational editing workflow.\n\n## The Bottom Line\n\nBest image generator for ChatGPT users — zero extra cost with Plus subscription. For artistic quality, Midjourney wins. For programmatic generation, DALL-E 3 API is the most mature option. Best text-in-image rendering of any generator.`
},
{
slug:'stable-diffusion',name:'Stable Diffusion',category:'image',icon:'🔓',iconBg:'rgba(138,43,226,0.15)',iconColor:'#8A2BE2',rating:4.3,priceLabel:'Free (open-source) – $10/mo',
description:'The leading open-source AI image generator, offering unlimited free local generation with complete creative control and no content restrictions.',
keywords:['open source','image generation','local','free','customizable'],
verdict:'Best for technical users who want unlimited free image generation with no restrictions. Run locally for free or use cloud services. Steepest learning curve but maximum control.',
pros:['Completely free and open-source — run locally with no API costs','No content restrictions or style limitations','Massive ecosystem of community models, LoRAs, and extensions','Full control: inpainting, outpainting, ControlNet, custom models'],
cons:['Requires decent GPU (8GB+ VRAM) for local generation','Steep learning curve — ComfyUI/Automatic1111 setup is not beginner-friendly','Base model quality trails Midjourney without fine-tuning','No official support — community-driven troubleshooting only'],
pricing:[{name:'Open Source',price:'$0',summary:'Run locally forever.',featured:true,features:['Unlimited generation','All models','Full control','No restrictions'],notIncluded:['Cloud GPU','Support','Easy UI']},{name:'DreamStudio',price:'$10/mo',summary:'Cloud-hosted by Stability AI.',featured:false,features:['1,000 credits/mo','Web UI','No GPU needed','Latest models'],notIncluded:['Unlimited generation']},{name:'API',price:'Pay-per-use',summary:'$0.002+ per image.',featured:false,features:['Programmatic access','All models','Batch generation'],notIncluded:[]}],
personas:[{icon:'🖥️',title:'Technical artists',description:'Artists comfortable with technical setup who want maximum creative control.'},{icon:'🎮',title:'Game developers',description:'Indie devs generating game assets without per-image costs.'},{icon:'🔬',title:'AI researchers',description:'Researchers experimenting with diffusion models and fine-tuning.'}],
websiteUrl:'https://stability.ai',scores:{price:98,ease:45,quality:80,integrations:82,support:40},
_engine:'SDXL / SD3',_api:'Yes (Stability AI)',_mobile:'No (local)',_team:'No',_support:'Community only',_privacy:'Local = full privacy',_integrations:'ComfyUI, A1111, API, thousands of plugins',_offline:'Yes (local)',_customTrain:'Yes (LoRA, Dreambooth, fine-tuning)',
body:`## Overview\n\nStable Diffusion is the open-source counterpart to Midjourney and DALL-E. Released by Stability AI in 2022, it democratized AI image generation by allowing anyone to run it locally for free. By 2026, its ecosystem of community models, extensions, and workflows is unmatched.\n\n## Use Cases\n\nPower users on r/StableDiffusion generate everything from game assets to product mockups to artistic illustrations. The open-source nature means no content restrictions. Game developers use it for unlimited asset generation. Researchers use it for fine-tuning experiments.\n\n## The Bottom Line\n\nFree and unlimited if you have the hardware and patience. Best for technical users who want control. Beginners should start with DALL-E 3 (via ChatGPT) or Midjourney. Cloud option via DreamStudio at $10/mo for non-technical users.`
},
{
slug:'leonardo-ai',name:'Leonardo.ai',category:'image',icon:'🦁',iconBg:'rgba(148,103,255,0.15)',iconColor:'#9467FF',rating:4.2,priceLabel:'Free – $60/mo',
description:'AI image generator optimized for gaming, fantasy, and concept art with real-time canvas editing and community-trained fine-tuned models.',
keywords:['image generation','gaming','fantasy','concept art','real-time'],
verdict:'Best for game art and fantasy content. Free tier is generous (150 images/day). Real-time canvas is a unique feature. Quality sits between DALL-E 3 and Midjourney.',
pros:['Free tier offers 150 images/day — most generous free option','Real-time Canvas for interactive image editing','Community fine-tuned models for specific art styles','Strong at gaming, fantasy, and character design'],
cons:['General-purpose quality trails Midjourney','Less effective for photorealistic content','Smaller community than Midjourney or Stable Diffusion','Enterprise features still maturing'],
pricing:[{name:'Free',price:'$0',summary:'150 images/day.',featured:false,features:['150 daily tokens','Basic models','Community models'],notIncluded:['Priority generation','Premium models']},{name:'Apprentice',price:'$12/mo',summary:'Regular creators.',featured:true,features:['8,500 tokens/mo','Premium models','Priority generation','Private generations'],notIncluded:['API']},{name:'Artisan',price:'$30/mo',summary:'Professional creators.',featured:false,features:['25,000 tokens/mo','All features','API access'],notIncluded:[]},{name:'Maestro',price:'$60/mo',summary:'Studios.',featured:false,features:['60,000 tokens/mo','Everything','Priority support'],notIncluded:[]}],
personas:[{icon:'🎮',title:'Game artists',description:'Game developers creating character art, environments, and item designs.'},{icon:'📖',title:'Fantasy/sci-fi creators',description:'Authors and artists generating book covers and concept art.'},{icon:'🎬',title:'Concept artists',description:'Professionals creating visual concepts for pitches and productions.'}],
websiteUrl:'https://leonardo.ai',scores:{price:85,ease:82,quality:80,integrations:60,support:62},
_engine:'Proprietary + SD-based',_api:'Yes',_mobile:'No',_team:'No',_support:'Discord + email',_privacy:'Standard',_integrations:'API, Discord',_offline:'No',_customTrain:'Community models',
body:`## Overview\n\nLeonardo.ai launched in 2023 as an AI image generator focused on gaming and fantasy art. By 2026, it serves over 10M users with the most generous free tier in the market (150 images/day). The Real-time Canvas feature allows interactive image editing.\n\n## Use Cases\n\nGame developers, fantasy artists, and concept designers are the core users. Reddit's r/Leonardo_AI praises the gaming-optimized models. Product Hunt reviews highlight the free tier generosity. Used for character design, environment art, and concept visualization.\n\n## The Bottom Line\n\nBest free option for image generation and strongest for gaming/fantasy art. $12/mo Apprentice for professionals. For general photorealism, Midjourney is superior. For API needs, DALL-E 3 or Stable Diffusion are better choices.`
},
{
slug:'adobe-firefly',name:'Adobe Firefly',category:'image',icon:'🔥',iconBg:'rgba(255,48,0,0.15)',iconColor:'#FF3000',rating:4.3,priceLabel:'Free – included in CC ($55/mo)',
description:'Adobe\'s generative AI engine integrated across Photoshop, Illustrator, and Express, trained exclusively on licensed content for commercial safety.',
keywords:['adobe','image generation','photoshop','commercially safe','design'],
verdict:'The only AI image generator guaranteed safe for commercial use. Essential for Adobe CC subscribers. Standalone quality trails Midjourney but the Photoshop integration is unmatched.',
pros:['Trained on licensed Adobe Stock — IP indemnity for commercial use','Generative Fill in Photoshop is the best AI editing integration','Seamless across Photoshop, Illustrator, Express, and InDesign','Style Reference and Structure Reference for precise control'],
cons:['Standalone image quality trails Midjourney and DALL-E 3','Requires Adobe CC subscription for full power','Limited free credits (25/month) without CC subscription','More conservative/generic outputs than competitors'],
pricing:[{name:'Free',price:'$0',summary:'25 monthly credits.',featured:false,features:['25 credits/mo','Web app','Basic generation'],notIncluded:['Photoshop integration','Premium features']},{name:'Premium',price:'$5/mo',summary:'100 monthly credits.',featured:false,features:['100 credits/mo','All web features','No watermarks'],notIncluded:['Photoshop integration']},{name:'CC All Apps',price:'$55/mo',summary:'Full Adobe Creative Cloud.',featured:true,features:['1,000 credits/mo','Generative Fill in Photoshop','All Adobe apps','Commercial license'],notIncluded:[]}],
personas:[{icon:'🎨',title:'Professional designers',description:'Designers already using Adobe CC who want AI integrated into Photoshop and Illustrator.'},{icon:'📷',title:'Photographers',description:'Photographers using Generative Fill for retouching and expanding images.'},{icon:'🏢',title:'Marketing teams',description:'Teams needing commercially safe AI-generated assets with IP indemnity.'}],
websiteUrl:'https://firefly.adobe.com',scores:{price:58,ease:85,quality:78,integrations:95,support:85},
_engine:'Adobe Firefly',_api:'Firefly API',_mobile:'Via Adobe apps',_team:'Via CC Teams',_support:'Adobe support',_privacy:'Enterprise-grade',_integrations:'Photoshop, Illustrator, Express, InDesign, API',_offline:'No',_customTrain:'Style references',
body:`## Overview\n\nAdobe Firefly is the generative AI engine powering creative features across Adobe's suite. Unlike competitors, it's trained exclusively on licensed Adobe Stock content, offering IP indemnity for commercial use — a critical differentiator for professional designers and enterprises.\n\n## Use Cases\n\nPhotoshop's Generative Fill is the killer app — extend images, remove objects, and add elements with AI. Designers use it for rapid prototyping, asset creation, and photo retouching. r/photoshop users call Generative Fill "the most useful Photoshop feature in a decade."\n\n## The Bottom Line\n\nEssential for Adobe CC subscribers. The only commercially safe AI image generator with IP indemnity. Standalone quality trails Midjourney, but the Photoshop integration makes it indispensable for professional design workflows.`
},
];
